# Generated by Django 4.0.4 on 2022-05-16 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prices',
            new_name='price',
        ),
    ]
