# Generated by Django 4.0.4 on 2022-05-28 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('RE', 'Received'), ('SH', 'Shipped'), ('IT', 'In_Transit'), ('DE', 'Delivered')], default='RE', max_length=2),
        ),
    ]
